version: 2.1

executors:
  default:
    docker:
      - image: cimg/node:16.15.1

commands:
  yarn_install:
    parameters:
      directory:
        description: yarn install directory
        type: string
    steps:
      - restore_cache:
          key: yarn-deps-cache-{{ checksum "package.json" }}
      - run:
          command: |
            cd <<parameters.directory>>
            yarn install
      - save_cache:
          key: yarn-deps-cache-{{ checksum "package.json" }}
          paths:
              - <<parameters.directory>>/node_modules

jobs:
  test:
    executor: default
    steps:
      - checkout
      - yarn_install:
          directory: web
      - run:
          working_directory: web
          command: yarn test:unit

workflows:
  main:
    jobs:
      - test
