version: 2.1

executors:
  default:
    docker:
      - image: cypress/base:16.14.0

commands:
  yarn_install:
    parameters:
      directory:
        description: yarn install directory
        type: string
    steps:
      - restore_cache:
          key: v2-yarn-<<parameters.directory>>-cache-{{ checksum "<<parameters.directory>>/package.json" }}
      - run:
          command: |
            cd <<parameters.directory>>
            yarn install
      - save_cache:
          key: v2-yarn-<<parameters.directory>>-cache-{{ checksum "<<parameters.directory>>/package.json" }}
          paths:
              - <<parameters.directory>>/node_modules
              - <<parameters.directory>>/.cache

jobs:
  test:
    executor: default
    steps:
      - checkout
      - yarn_install:
          directory: web
      - run:
          working_directory: web
          command: yarn test:unit
      - run:
          working_directory: web
          command: yarn test:e2e

workflows:
  main:
    jobs:
      - test
