version: 2.1

executors:
  default:
    docker:
      - image: cimg/node:16

commands:
  yarn_install:
    working_directory: ~/my-app
    steps:
      - restore_cache:
          key: yarn-deps-cache-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          key: yarn-deps-cache-{{ checksum "package.json" }}
          paths:
              - node_modules

jobs:
  test:
    executor: default
    steps:
      - checkout
      - yarn_install
      - run: yarn test:unit

workflows:
  main:
    jobs:
      - test
